import type { IndustryContent } from "./types";

export const industries: IndustryContent[] = [
  {
    slug: "legal",
    nav: "Legal",
    icon: "Gavel",
    metaTitle: "AI for Law Firms Australia | Legal AI Automation | XoomAgent™ by XoomAI",
    metaDescription:
      "AI for Australian law firms. XoomAgent™ automates client intake, document review, conflict checks, deadline tracking and after-hours enquiries — securely, with full audit trails.",
    keyword: "AI for law firms Australia",
    cardSummary: "Client intake, document review, conflict checks, deadline tracking and after-hours enquiry handling for law firms.",
    h1: "An AI Employee for Your Law Firm",
    heroSubtitle:
      "XoomAgent™ handles client intake, first-pass document review, conflict checks and after-hours enquiries — so your lawyers spend more time on billable work and less on admin.",
    heroStats: [
      { value: "24/7", label: "Intake & enquiries" },
      { value: "First-pass", label: "Document review" },
      { value: "Audited", label: "Every action logged" },
      { value: "AU-hosted", label: "Data sovereignty" },
    ],
    pains: [
      { title: "Client intake eats fee-earner time", body: "Qualifying enquiries, collecting details and opening matters pulls solicitors and paralegals off billable work." },
      { title: "Document review is slow and manual", body: "First-pass review of contracts, bundles and disclosure consumes hours that could be spent on advice." },
      { title: "After-hours enquiries go cold", body: "Prospective clients call or email outside hours and move on to the firm that responds first." },
      { title: "Deadlines and conflicts carry real risk", body: "Missed limitation dates or conflict checks aren't just embarrassing — they're a professional liability." },
    ],
    automations: [
      { icon: "UserCheck", title: "Client Intake & Qualification", description: "Capture enquiry details, run initial qualification and open a matter file — 24/7, straight into your practice system." },
      { icon: "FileSearch", title: "First-Pass Document Review", description: "Summarise contracts and bundles, extract key clauses and flag issues for a lawyer to review." },
      { icon: "Scale", title: "Conflict Checks", description: "Cross-reference parties against your existing matters and flag potential conflicts before you act." },
      { icon: "CalendarClock", title: "Deadline & Limitation Tracking", description: "Track key dates and limitation periods with proactive reminders to the responsible fee-earner." },
      { icon: "AlarmClock", title: "After-Hours Enquiry Handling", description: "Answer common questions, capture details and book consultations outside business hours." },
      { icon: "FileText", title: "Document Drafting Assistance", description: "Draft standard letters, engagement documents and templates from a short brief for lawyer sign-off." },
      { icon: "Mail", title: "Email & Correspondence Triage", description: "Sort, summarise and route incoming correspondence to the right matter and fee-earner." },
    ],
    workflows: [
      { title: "New client enquiry → opened matter", steps: ["Enquiry arrives via web, phone or email", "Agent qualifies and captures key details", "Conflict check run against existing matters", "Matter opened and consultation booked", "Fee-earner notified with a clean summary"] },
      { title: "Contract review request", steps: ["Document uploaded to the agent", "Key clauses and dates extracted", "Risks and unusual terms flagged", "Plain-English summary produced", "Lawyer reviews and advises"] },
    ],
    modules: ["Client Intake Agent", "Document Intelligence", "Conflict & Compliance Checks", "Deadline Tracker", "After-Hours Reception"],
    compliance: [
      "Dedicated, isolated infrastructure — not shared multi-tenant AI",
      "No model training on client or matter data",
      "Australian data sovereignty and Privacy Act–first handling",
      "Full audit trails for every action the agent takes",
      "Permissioned, least-privilege access to matter data",
      "Designed with legal professional privilege and confidentiality in mind",
    ],
    integrations: ["Microsoft 365", "SharePoint", "Outlook", "Practice management systems", "Document management systems", "Websites & intake forms"],
    faqs: [
      { q: "Is client confidentiality and privilege protected?", a: "Yes. XoomAgent™ runs on dedicated, isolated infrastructure with permissioned access, full audit logging and no model training on your data. It's designed with confidentiality and privilege front of mind." },
      { q: "Will it replace our paralegals?", a: "No. It removes repetitive intake and review work so your paralegals and solicitors focus on judgement, advice and client relationships." },
      { q: "Can it work with our practice management system?", a: "In most cases, yes — via integration or secure API. We scope your specific systems during the free AI Workflow Audit." },
      { q: "Does a lawyer still review the output?", a: "Always. The agent does first-pass work and drafting; a qualified lawyer reviews and signs off on anything that constitutes advice or final documents." },
    ],
  },

  {
    slug: "financial",
    nav: "Financial Services",
    icon: "Banknote",
    metaTitle: "AI for Financial Advisers & Accountants Australia | XoomAgent™ by XoomAI",
    metaDescription:
      "AI for Australian financial advisers and accounting firms. XoomAgent™ automates data entry, compliance documentation, client reporting and review preparation — securely and Privacy Act focused.",
    keyword: "AI for financial advisers Australia",
    cardSummary: "Data entry automation, compliance documentation, client reporting and financial analysis for advisers and accounting firms.",
    h1: "An AI Employee for Financial Advisers & Accountants",
    heroSubtitle:
      "XoomAgent™ automates data entry, compliance paperwork, client reporting and review prep — freeing your advisers and accountants to focus on advice and client relationships.",
    heroStats: [
      { value: "Hours", label: "Saved on data entry" },
      { value: "Faster", label: "Client reporting" },
      { value: "Audited", label: "Compliance-ready" },
      { value: "AU-hosted", label: "Data sovereignty" },
    ],
    pains: [
      { title: "Data entry swallows billable hours", body: "Rekeying figures between source documents, spreadsheets and software is slow, manual and error-prone." },
      { title: "Compliance paperwork piles up", body: "Producing and maintaining advice documentation and records is time-consuming and easy to fall behind on." },
      { title: "Client reporting is manual", body: "Pulling together statements and review packs by hand delays clients and frustrates staff." },
      { title: "Review prep is repetitive", body: "Preparing for client reviews means the same gathering and summarising of data every cycle." },
    ],
    automations: [
      { icon: "Receipt", title: "Document Data Extraction", description: "Pull figures from statements, invoices and forms straight into your systems with review checkpoints." },
      { icon: "FileCheck2", title: "Compliance Documentation", description: "Assemble and maintain advice and record-keeping documents from your templates, ready for sign-off." },
      { icon: "BarChart3", title: "Client Reporting", description: "Generate client statements and review packs automatically from your data, on schedule." },
      { icon: "ClipboardList", title: "Review Preparation", description: "Gather and summarise each client's position ahead of reviews so advisers walk in prepared." },
      { icon: "Mail", title: "Client Communications", description: "Draft and send updates, reminders and follow-ups on brand, with the right disclaimers." },
      { icon: "Search", title: "Anomaly & Exception Flagging", description: "Surface unusual transactions or data that needs a human to check before it's processed." },
      { icon: "UserCheck", title: "Onboarding & Fact-Find", description: "Collect new-client information and documents through a guided, secure intake." },
    ],
    workflows: [
      { title: "Statement → reconciled data", steps: ["Document received from client or institution", "Agent extracts and structures the data", "Figures matched and exceptions flagged", "Clean data pushed to your software", "Accountant reviews exceptions only"] },
      { title: "Quarterly client review pack", steps: ["Agent pulls latest client data", "Performance and position summarised", "Report generated from your template", "Adviser reviews and personalises", "Pack sent to client on schedule"] },
    ],
    modules: ["Document Intelligence", "Compliance Document Builder", "Client Reporting Agent", "Onboarding & Fact-Find", "Exception Flagging"],
    compliance: [
      "Dedicated, isolated infrastructure for sensitive financial data",
      "No model training on client financial data",
      "Australian data sovereignty and Privacy Act–first handling",
      "Full audit trails to support your compliance obligations",
      "Permissioned access scoped to each workflow",
      "Human review checkpoints on anything that affects advice or records",
    ],
    integrations: ["Microsoft 365", "Xero", "MYOB", "SharePoint", "CRM systems", "Practice & planning software", "Secure client portals"],
    faqs: [
      { q: "Is our clients' financial data secure?", a: "Yes. Data runs on dedicated, isolated infrastructure with permissioned access, full audit trails and no model training on your data — built by a managed security provider." },
      { q: "Can it integrate with Xero or MYOB?", a: "In most cases, yes, via secure integration or API. We confirm your exact stack during the free AI Workflow Audit." },
      { q: "Does this give financial advice?", a: "No. XoomAgent™ handles the administrative and preparatory work. Advice and final documents remain with your qualified advisers, who review and sign off." },
      { q: "How does it help with compliance?", a: "It assembles and maintains documentation from your templates and keeps a complete audit trail of actions — supporting, not replacing, your compliance processes." },
    ],
  },

  {
    slug: "logistics",
    nav: "Logistics & Transport",
    icon: "Truck",
    metaTitle: "AI for Logistics & Transport Australia | XoomAgent™ by XoomAI",
    metaDescription:
      "AI for Australian logistics and transport operators. XoomAgent™ automates shipment tracking updates, carrier communication, proof-of-delivery handling and warehouse admin — 24/7.",
    keyword: "AI for logistics companies Australia",
    cardSummary: "Shipment tracking, carrier communication, proof-of-delivery handling and warehouse admin automation.",
    h1: "An AI Employee for Logistics & Transport",
    heroSubtitle:
      "XoomAgent™ keeps customers updated, chases carriers, processes proof-of-delivery and handles the constant admin of moving freight — so your team can focus on operations, not the inbox.",
    heroStats: [
      { value: "24/7", label: "Status updates" },
      { value: "Auto", label: "Carrier chasing" },
      { value: "Faster", label: "POD processing" },
      { value: "Fewer", label: "Where-is-my-order calls" },
    ],
    pains: [
      { title: "‘Where is my delivery?’ never stops", body: "Customers and partners constantly ask for status, and staff spend hours looking it up and replying." },
      { title: "Carrier coordination is manual", body: "Chasing carriers, confirming bookings and handling exceptions clogs inboxes and phone lines." },
      { title: "Proof-of-delivery admin lags", body: "Collecting, matching and filing PODs delays invoicing and ties up admin staff." },
      { title: "After-hours exceptions go unmanaged", body: "Delays and issues outside business hours sit unaddressed until the morning." },
    ],
    automations: [
      { icon: "Truck", title: "Shipment Status Updates", description: "Answer ‘where is my order’ instantly and send proactive status updates to customers and partners." },
      { icon: "PhoneCall", title: "Carrier Communication", description: "Chase bookings, confirm pickups and follow up on exceptions across carriers automatically." },
      { icon: "FileCheck2", title: "Proof-of-Delivery Handling", description: "Collect, match and file PODs, then trigger invoicing — no manual chasing." },
      { icon: "AlarmClock", title: "After-Hours Exception Handling", description: "Capture and triage delays and issues outside hours, escalating the urgent ones." },
      { icon: "Mail", title: "Quote & Booking Enquiries", description: "Respond to freight quote and booking enquiries 24/7 and route qualified jobs to your team." },
      { icon: "ClipboardList", title: "Warehouse Admin", description: "Automate routine warehouse paperwork, stock queries and documentation." },
      { icon: "RefreshCw", title: "System Sync", description: "Keep your TMS, CRM and customer records in sync as shipments progress." },
    ],
    workflows: [
      { title: "Customer status enquiry", steps: ["Customer asks for an update", "Agent looks up live status", "Clear, branded reply sent instantly", "Proactive update scheduled for next milestone", "Exceptions escalated to ops"] },
      { title: "Delivery → invoice", steps: ["POD received from driver or carrier", "Agent matches it to the consignment", "Document filed against the job", "Invoicing triggered automatically", "Discrepancies flagged for review"] },
    ],
    modules: ["Status & Tracking Agent", "Carrier Comms", "POD & Invoicing", "After-Hours Exceptions", "Quote & Booking Intake"],
    compliance: [
      "Dedicated, isolated infrastructure for operational data",
      "No model training on your shipment or customer data",
      "Australian data sovereignty and Privacy Act–first handling",
      "Full audit trails across communications and updates",
      "Permissioned access to your TMS and customer systems",
      "Human escalation for high-value or sensitive exceptions",
    ],
    integrations: ["Transport management systems (TMS)", "Microsoft 365", "CRM systems", "Email & SMS", "Carrier portals", "REST APIs", "Webhooks"],
    faqs: [
      { q: "Can it connect to our TMS?", a: "In most cases, yes — via integration or API. We confirm exactly what's possible with your transport management system during the free AI Workflow Audit." },
      { q: "Will customers know they're talking to AI?", a: "You decide the tone and disclosure. The agent communicates clearly and on brand, and hands complex or sensitive issues to your team." },
      { q: "How does it handle exceptions and delays?", a: "It captures and triages issues automatically and escalates the urgent ones to the right person, including after hours, with a full log of what happened." },
      { q: "Is our operational data secure?", a: "Yes. Everything runs on dedicated, isolated infrastructure with audit trails and no model training on your data." },
    ],
  },

  {
    slug: "healthcare",
    nav: "Healthcare",
    icon: "HeartPulse",
    metaTitle: "AI for Medical Practices & Healthcare Australia | XoomAgent™ by XoomAI",
    metaDescription:
      "AI for Australian medical and allied health practices. XoomAgent™ automates appointment scheduling, patient intake, recalls and after-hours enquiries — privacy-first and securely managed.",
    keyword: "AI for medical practices Australia",
    cardSummary: "Appointment scheduling, patient intake, recall campaigns and after-hours patient support for healthcare providers.",
    h1: "An AI Employee for Medical & Allied Health Practices",
    heroSubtitle:
      "XoomAgent™ handles appointment scheduling, patient intake, recalls and after-hours enquiries — reducing front-desk pressure while keeping patient data private and secure.",
    heroStats: [
      { value: "24/7", label: "Patient enquiries" },
      { value: "Fewer", label: "Missed appointments" },
      { value: "Faster", label: "Intake & recalls" },
      { value: "Privacy-first", label: "AU data handling" },
    ],
    pains: [
      { title: "The front desk is overwhelmed", body: "Phones, scheduling, intake and enquiries all hit reception at once, creating bottlenecks and burnout." },
      { title: "No-shows cost real money", body: "Missed appointments and weak reminders leave gaps that are hard to fill at short notice." },
      { title: "Recalls slip through the cracks", body: "Manual recall and follow-up campaigns are easy to delay, affecting patient outcomes and revenue." },
      { title: "After-hours enquiries go unanswered", body: "Patients with questions outside hours wait, or go elsewhere." },
    ],
    automations: [
      { icon: "CalendarClock", title: "Appointment Scheduling", description: "Book, reschedule and confirm appointments 24/7, with smart reminders to cut no-shows." },
      { icon: "ClipboardList", title: "Patient Intake", description: "Collect intake details and forms securely before the visit, ready for the practitioner." },
      { icon: "RefreshCw", title: "Recall & Follow-Up Campaigns", description: "Run recall and follow-up reminders automatically so patients get timely care." },
      { icon: "AlarmClock", title: "After-Hours Enquiries", description: "Answer common questions and capture details after hours, escalating anything urgent." },
      { icon: "Mail", title: "Patient Communications", description: "Send appointment, preparation and follow-up messages on brand and on time." },
      { icon: "Phone", title: "Phone & Reception Overflow", description: "Handle overflow enquiries so reception isn't stuck on hold queues all day." },
      { icon: "FileText", title: "Documentation Support", description: "Draft routine correspondence and summaries for staff review." },
    ],
    workflows: [
      { title: "New patient booking", steps: ["Patient enquires online or by phone", "Agent offers available times and books", "Secure intake form sent and completed", "Reminders scheduled to reduce no-shows", "Practice notified with a clean summary"] },
      { title: "Recall campaign", steps: ["Due-for-recall list identified", "Personalised reminders sent", "Bookings captured automatically", "Non-responders followed up", "Outcomes logged for the practice"] },
    ],
    modules: ["Scheduling Agent", "Patient Intake", "Recall & Follow-Up", "After-Hours Reception", "Patient Comms"],
    compliance: [
      "Dedicated, isolated infrastructure for sensitive health data",
      "No model training on patient data",
      "Australian data sovereignty with a privacy-first approach",
      "Designed around Australian Privacy Principles and health record sensitivity",
      "Full audit trails and permissioned access",
      "Clinical decisions always stay with your practitioners",
    ],
    integrations: ["Practice management systems", "Microsoft 365", "SMS & email", "Online booking systems", "Secure forms", "Phone systems"],
    faqs: [
      { q: "How is sensitive patient data protected?", a: "XoomAgent™ runs on dedicated, isolated infrastructure with permissioned access, audit trails and no model training on patient data. It's designed around the Australian Privacy Principles and the sensitivity of health information." },
      { q: "Does it make clinical decisions?", a: "No. It handles scheduling, intake, reminders and admin. All clinical judgement and care remains entirely with your practitioners." },
      { q: "Can it integrate with our practice management system?", a: "In many cases, yes — via integration or API. We confirm what's possible with your specific system during the free AI Workflow Audit." },
      { q: "Will it reduce no-shows?", a: "Yes — smart, timely reminders and easy rescheduling consistently reduce missed appointments and help fill gaps." },
    ],
  },

  {
    slug: "real-estate",
    nav: "Real Estate",
    icon: "Home",
    metaTitle: "AI for Real Estate Agencies Australia | XoomAgent™ by XoomAI",
    metaDescription:
      "AI for Australian real estate agencies. XoomAgent™ delivers instant listing enquiry responses, sub-5-minute lead follow-up, AI market reports and tenant comms — 24/7, from $2,399/month.",
    keyword: "AI for real estate agencies Australia",
    cardSummary: "Listing enquiries, instant lead follow-up, market reports and tenant communications for agencies and property managers.",
    h1: "Your Real Estate Agency Deserves an AI Employee",
    heroSubtitle:
      "XoomAgent™ responds to every listing enquiry instantly, follows up leads in under five minutes, generates market reports and handles tenant communications — capturing the opportunities you're currently missing.",
    heroStats: [
      { value: "<5 min", label: "Lead follow-up" },
      { value: "24/7", label: "Enquiry capture" },
      { value: "Instant", label: "Listing responses" },
      { value: "$2,399/mo", label: "From — less than part-time admin" },
    ],
    pains: [
      { title: "Listing enquiries go to voicemail", body: "Buyers enquire when agents are at inspections or with clients, and the lead goes cold before anyone calls back." },
      { title: "Slow follow-up kills conversion", body: "Leads contacted after the first few minutes convert far less. Manual follow-up simply can't keep pace." },
      { title: "After-hours opportunities are missed", body: "Evenings and weekends are when buyers browse — and when most agencies stop responding." },
      { title: "Tenant comms and reports are manual", body: "Property managers and agents lose hours to routine tenant messages, market reports and appraisals." },
    ],
    automations: [
      { icon: "Mailbox", title: "Instant Listing Enquiry Response", description: "Every portal and website enquiry answered immediately with property details and next steps." },
      { icon: "UserCheck", title: "Sub-5-Minute Lead Follow-Up", description: "Qualify and follow up leads within minutes, then push them into your CRM ready for the agent." },
      { icon: "AlarmClock", title: "24/7 After-Hours Capture", description: "Engage and qualify buyers in the evenings and on weekends — never miss a hot lead again." },
      { icon: "BarChart3", title: "AI Market Reports & CMAs", description: "Generate market reports and comparative appraisals on demand from your data sources." },
      { icon: "Home", title: "Tenant & Property Management", description: "Handle routine tenant enquiries, maintenance requests and updates automatically." },
      { icon: "RefreshCw", title: "Database Reactivation", description: "Re-engage your past-appraisal and dormant database with timely, personalised nurture." },
      { icon: "CalendarClock", title: "Inspection & Appraisal Booking", description: "Book inspections and appraisals around the clock straight into agent calendars." },
    ],
    workflows: [
      { title: "Portal enquiry → booked inspection", steps: ["Buyer enquires via a portal or your site", "Agent replies instantly with details", "Buyer qualified and intent captured", "Inspection booked into the agent's calendar", "Lead and notes synced to your CRM"] },
      { title: "Listing won → appraisal pipeline", steps: ["Appraisal request received", "AI market report and CMA generated", "Appointment booked with the agent", "Follow-up nurture scheduled", "Outcome tracked in the CRM"] },
    ],
    modules: ["Listing Enquiry Agent", "Lead Follow-Up", "After-Hours Capture", "Market Report Generator", "Property Management Comms", "Database Reactivation"],
    compliance: [
      "Dedicated, isolated infrastructure — non-shared",
      "No model training on agency, vendor or tenant data",
      "Australian data sovereignty and Privacy Act–first handling",
      "Full audit trails on enquiries and communications",
      "Permissioned access to your CRM and listings data",
      "Human handoff for negotiations and sensitive conversations",
    ],
    integrations: ["Rex", "Agentbox", "PropertyMe", "Palace", "Console", "RP Data", "Pricefinder", "Microsoft 365", "Major property portals"],
    faqs: [
      { q: "How fast does it follow up on leads?", a: "Within minutes — typically under five — which is where the biggest lift in conversion comes from. The agent qualifies the lead and hands a warm, informed prospect to your salesperson." },
      { q: "Does it integrate with Rex, Agentbox or PropertyMe?", a: "Yes — XoomAgent™ is designed to work with the systems Australian agencies use, including Rex, Agentbox, PropertyMe, Palace and more. We confirm your stack during the audit." },
      { q: "What does it cost?", a: "XoomAgent™ for Real Estate starts from $2,399/month — less than a part-time admin — and includes a 30-day satisfaction guarantee. Final scope is confirmed in your free audit." },
      { q: "Will buyers feel like they're talking to a bot?", a: "No. Conversations are natural, on brand and helpful, and anything sensitive — like negotiations — is handed straight to your agent." },
    ],
  },

  {
    slug: "construction",
    nav: "Construction",
    icon: "HardHat",
    metaTitle: "AI for Construction Companies Australia | XoomAgent™ by XoomAI",
    metaDescription:
      "AI for Australian builders and contractors. XoomAgent™ automates quote requests, supplier coordination, site documentation and compliance tracking — so you spend less time in the office.",
    keyword: "AI for construction companies Australia",
    cardSummary: "Quote requests, supplier coordination, site reporting and compliance tracking for builders and contractors.",
    h1: "An AI Employee for Builders & Contractors",
    heroSubtitle:
      "XoomAgent™ handles quote requests, chases suppliers, organises site documentation and tracks compliance — cutting the office admin that keeps you off the tools and off the site.",
    heroStats: [
      { value: "Faster", label: "Quote turnaround" },
      { value: "24/7", label: "Enquiry capture" },
      { value: "Organised", label: "Site documentation" },
      { value: "Tracked", label: "Compliance & SWMS" },
    ],
    pains: [
      { title: "Quotes take too long to turn around", body: "Enquiries pile up while you're on site, and slow quotes mean lost jobs to faster competitors." },
      { title: "Supplier coordination is constant", body: "Chasing prices, orders and deliveries across suppliers eats into evenings and weekends." },
      { title: "Site documentation is a mess", body: "Photos, dockets, variations and reports live across phones and emails, hard to find when you need them." },
      { title: "Compliance tracking is risky when manual", body: "Keeping SWMS, inductions and certifications current by hand invites gaps and audit headaches." },
    ],
    automations: [
      { icon: "Mail", title: "Quote Request Handling", description: "Capture enquiry details 24/7, gather what's needed and prepare quote drafts for your sign-off." },
      { icon: "Truck", title: "Supplier Coordination", description: "Chase pricing, confirm orders and follow up deliveries across your suppliers automatically." },
      { icon: "ClipboardList", title: "Site Documentation", description: "Organise photos, dockets, variations and daily reports against the right job — searchable later." },
      { icon: "FileCheck2", title: "Compliance Tracking", description: "Track SWMS, inductions and certifications with reminders before anything lapses." },
      { icon: "UserCheck", title: "Lead Capture & Qualification", description: "Engage and qualify new enquiries so the right jobs reach you fast." },
      { icon: "CalendarClock", title: "Scheduling & Coordination", description: "Coordinate site visits, trades and inspections without the phone tag." },
      { icon: "RefreshCw", title: "Project Updates", description: "Send clients and stakeholders timely progress updates with minimal effort." },
    ],
    workflows: [
      { title: "Enquiry → quote", steps: ["Enquiry captured 24/7", "Scope and details gathered", "Supplier pricing requested where needed", "Quote draft prepared", "Builder reviews, adjusts and sends"] },
      { title: "Compliance check", steps: ["Certifications and SWMS tracked", "Upcoming expiries flagged early", "Reminders sent to responsible people", "Documents collected and filed", "Audit-ready record maintained"] },
    ],
    modules: ["Quote & Enquiry Agent", "Supplier Coordination", "Site Documentation", "Compliance Tracker", "Project Updates"],
    compliance: [
      "Dedicated, isolated infrastructure for project data",
      "No model training on your project or client data",
      "Australian data sovereignty and Privacy Act–first handling",
      "Audit trails across quotes, orders and documentation",
      "Permissioned access to job and supplier data",
      "Built to support — not replace — your WHS and compliance obligations",
    ],
    integrations: ["Microsoft 365", "Job management software", "Accounting (Xero / MYOB)", "Email & SMS", "Cloud storage", "Supplier portals"],
    faqs: [
      { q: "Can it work from site, on a phone?", a: "Yes. Capturing enquiries, photos, dockets and updates works from mobile, so documentation happens in the field instead of piling up for the office." },
      { q: "Will it help us win more quotes?", a: "Faster turnaround is one of the biggest levers in construction. By capturing enquiries 24/7 and preparing drafts quickly, you respond ahead of slower competitors." },
      { q: "Does it integrate with our job management software?", a: "In most cases, yes — via integration or API. We confirm your specific tools during the free AI Workflow Audit." },
      { q: "How does it help with compliance?", a: "It tracks SWMS, inductions and certifications, sends reminders before they lapse and keeps an audit-ready record — supporting your existing WHS processes." },
    ],
  },

  {
    slug: "hospitality",
    nav: "Hospitality",
    icon: "UtensilsCrossed",
    metaTitle: "AI for Hospitality, Restaurants & Hotels Australia | XoomAgent™ by XoomAI",
    metaDescription:
      "AI for Australian restaurants, cafes and hotels. XoomAgent™ manages reservations, guest enquiries, reviews and routine updates 24/7 — so your team focuses on service, not the inbox.",
    keyword: "AI for hospitality Australia",
    cardSummary: "Reservation management, guest enquiries, review responses and routine updates for restaurants and hotels.",
    h1: "An AI Employee for Hospitality Venues",
    heroSubtitle:
      "XoomAgent™ manages reservations, answers guest enquiries, responds to reviews and handles routine updates around the clock — so your team can focus on hospitality, not admin.",
    heroStats: [
      { value: "24/7", label: "Guest enquiries" },
      { value: "Instant", label: "Booking responses" },
      { value: "Fewer", label: "Missed reservations" },
      { value: "Faster", label: "Review responses" },
    ],
    pains: [
      { title: "Enquiries come at the worst times", body: "Booking and event questions arrive during service, when nobody can stop to answer the phone or inbox." },
      { title: "Missed messages mean missed revenue", body: "Unanswered booking and function enquiries quietly walk across the road to a competitor." },
      { title: "Reviews need timely responses", body: "Prompt, on-brand replies to reviews matter for reputation — but they're easy to neglect when you're busy." },
      { title: "Routine updates eat manager time", body: "Menu changes, hours, FAQs and confirmations are repetitive but constant." },
    ],
    automations: [
      { icon: "CalendarClock", title: "Reservation Management", description: "Take, confirm and modify bookings 24/7, with reminders to reduce no-shows." },
      { icon: "MessageSquare", title: "Guest Enquiries", description: "Answer questions about menus, hours, dietary options and events instantly, on brand." },
      { icon: "Briefcase", title: "Function & Event Enquiries", description: "Capture and qualify function enquiries, then route serious leads to your events team." },
      { icon: "TrendingUp", title: "Review Responses", description: "Draft prompt, on-brand responses to reviews for a quick human sign-off." },
      { icon: "RefreshCw", title: "Routine Updates", description: "Keep menus, hours and FAQs current across channels with minimal effort." },
      { icon: "Mail", title: "Guest Communications", description: "Send confirmations, reminders and post-visit follow-ups automatically." },
      { icon: "AlarmClock", title: "After-Hours Coverage", description: "Capture and respond to enquiries outside service hours so nothing is missed." },
    ],
    workflows: [
      { title: "Booking enquiry → confirmed table", steps: ["Guest enquires via phone, web or social", "Availability checked and offered", "Booking confirmed and logged", "Reminder scheduled to cut no-shows", "Special requests flagged to the venue"] },
      { title: "Function enquiry → qualified lead", steps: ["Function enquiry captured 24/7", "Key details and date gathered", "Suitability and budget qualified", "Serious lead routed to events team", "Follow-up scheduled automatically"] },
    ],
    modules: ["Reservation Agent", "Guest Enquiry", "Function & Events", "Review Responder", "After-Hours Coverage"],
    compliance: [
      "Dedicated, isolated infrastructure",
      "No model training on your guest data",
      "Australian data sovereignty and Privacy Act–first handling",
      "Audit trails across bookings and communications",
      "Permissioned access to booking and CRM systems",
      "Human handoff for complex events and complaints",
    ],
    integrations: ["Booking & reservation systems", "Microsoft 365", "Social & messaging channels", "Email & SMS", "POS / CRM where available", "Websites"],
    faqs: [
      { q: "Can it take bookings while we're in service?", a: "Yes — that's exactly the point. The agent handles enquiries and bookings 24/7, including during your busiest service periods, so the team stays on the floor." },
      { q: "Will responses sound like our venue?", a: "Yes. Tone and style are tuned to your brand, and anything sensitive — like a complaint or a complex event — is handed to a person." },
      { q: "Does it integrate with our booking system?", a: "In many cases, yes — via integration or API. We confirm your specific reservation system during the free AI Workflow Audit." },
      { q: "Can it help with online reviews?", a: "It drafts prompt, on-brand responses for your quick approval, helping you stay responsive without it becoming a daily chore." },
    ],
  },

  {
    slug: "retail",
    nav: "Retail",
    icon: "ShoppingCart",
    metaTitle: "AI for Retail & E-commerce Australia | XoomAgent™ by XoomAI",
    metaDescription:
      "AI for Australian retail and e-commerce. XoomAgent™ handles product questions, order support, returns and promotions 24/7 — and keeps your inventory queries and CRM up to date.",
    keyword: "AI for retail business Australia",
    cardSummary: "Product questions, order processing, customer support and promotional campaigns for retail and e-commerce.",
    h1: "An AI Employee for Retail & E-commerce",
    heroSubtitle:
      "XoomAgent™ answers product questions, supports orders and returns, runs promotions and keeps your systems updated — delivering 24/7 customer service without growing the team.",
    heroStats: [
      { value: "24/7", label: "Customer support" },
      { value: "Instant", label: "Product answers" },
      { value: "Faster", label: "Order & returns help" },
      { value: "Higher", label: "Conversion on enquiries" },
    ],
    pains: [
      { title: "Customer questions never stop", body: "Product, stock, shipping and returns questions flood every channel, all day and night." },
      { title: "Slow replies lose sales", body: "Shoppers comparing options buy from whoever answers first — delays cost conversions." },
      { title: "Order and returns support is repetitive", body: "The same ‘where's my order’ and returns queries consume your support team's day." },
      { title: "Promotions take effort to run", body: "Coordinating and communicating campaigns across channels is fiddly and time-consuming." },
    ],
    automations: [
      { icon: "MessageSquare", title: "Product & Stock Questions", description: "Answer product, sizing, availability and shipping questions instantly across your channels." },
      { icon: "ShoppingCart", title: "Order Support", description: "Handle ‘where's my order’, changes and tracking enquiries automatically, 24/7." },
      { icon: "RefreshCw", title: "Returns & Exchanges", description: "Guide customers through returns and exchanges with clear, on-brand steps." },
      { icon: "UserCheck", title: "Lead Capture & Conversion", description: "Engage browsing shoppers, answer objections and nudge them to purchase." },
      { icon: "TrendingUp", title: "Promotional Campaigns", description: "Coordinate and communicate promotions across email, SMS and chat." },
      { icon: "Database", title: "Inventory & CRM Queries", description: "Surface stock and customer information and keep records updated as orders flow." },
      { icon: "AlarmClock", title: "After-Hours Service", description: "Provide instant help overnight and on weekends when staff aren't online." },
    ],
    workflows: [
      { title: "Pre-sale question → sale", steps: ["Shopper asks a product question", "Agent answers with accurate details", "Objections handled and options suggested", "Shopper guided to checkout", "Lead and context captured in your CRM"] },
      { title: "Order enquiry → resolution", steps: ["Customer asks about an order", "Agent looks up status and details", "Clear update or next step provided", "Returns or changes processed where allowed", "Complex cases escalated to staff"] },
    ],
    modules: ["Customer Support Agent", "Order & Returns", "Pre-Sale Conversion", "Promotions", "After-Hours Service"],
    compliance: [
      "Dedicated, isolated infrastructure",
      "No model training on your customer data",
      "Australian data sovereignty and Privacy Act–first handling",
      "Audit trails across customer interactions",
      "Permissioned access to order and CRM systems",
      "Human handoff for complaints and complex cases",
    ],
    integrations: ["Shopify / WooCommerce", "Microsoft 365", "Email & SMS", "Live chat", "CRM systems", "Inventory systems", "Websites"],
    faqs: [
      { q: "Does it connect to our e-commerce platform?", a: "In most cases, yes — including platforms like Shopify and WooCommerce, via integration or API. We confirm your setup during the free AI Workflow Audit." },
      { q: "Can it actually help increase sales?", a: "Yes. Instant, accurate answers to pre-sale questions and proactive engagement of browsing shoppers consistently lift conversion on enquiries." },
      { q: "How does it handle returns?", a: "It guides customers through your returns and exchange policy step by step, processing what's allowed and escalating anything that needs a person." },
      { q: "Is customer data secure?", a: "Yes. Everything runs on dedicated, isolated infrastructure with audit trails and no model training on your customer data." },
    ],
  },

  {
    slug: "professional-services",
    nav: "Professional Services",
    icon: "Briefcase",
    metaTitle: "AI for Professional Services & Consultancies Australia | XoomAgent™ by XoomAI",
    metaDescription:
      "AI for Australian consultancies and agencies. XoomAgent™ automates proposal generation, client onboarding, project tracking and reporting — so your experts spend more time on billable work.",
    keyword: "AI for professional services Australia",
    cardSummary: "Proposal generation, client onboarding, project tracking and reporting for consultancies and agencies.",
    h1: "An AI Employee for Professional Services Firms",
    heroSubtitle:
      "XoomAgent™ drafts proposals, onboards clients, tracks projects and compiles reports — removing the admin that pulls your consultants and account managers off billable, high-value work.",
    heroStats: [
      { value: "Faster", label: "Proposal turnaround" },
      { value: "Smoother", label: "Client onboarding" },
      { value: "More", label: "Billable hours freed" },
      { value: "Auto", label: "Status reporting" },
    ],
    pains: [
      { title: "Proposals take too long", body: "Drafting and tailoring proposals by hand slows your pipeline and delays revenue." },
      { title: "Onboarding is inconsistent", body: "Every new client means the same scramble of forms, access and kickoff admin — done differently each time." },
      { title: "Project status is hard to keep current", body: "Pulling together status updates and reports steals time from delivery." },
      { title: "Admin eats billable hours", body: "Your most valuable people spend too much of the week on coordination instead of expert work." },
    ],
    automations: [
      { icon: "FileText", title: "Proposal Generation", description: "Draft tailored proposals and scopes from a short brief and your templates for fast sign-off." },
      { icon: "UserCheck", title: "Client Onboarding", description: "Run a consistent onboarding — forms, documents, access and kickoff — every single time." },
      { icon: "ClipboardList", title: "Project Tracking", description: "Keep project status current and surface what needs attention without manual chasing." },
      { icon: "BarChart3", title: "Status Reporting", description: "Compile client and internal reports automatically from your project data." },
      { icon: "Mail", title: "Client Communications", description: "Draft and send updates, follow-ups and meeting summaries on brand." },
      { icon: "Search", title: "Research & Synthesis", description: "Summarise documents and research to accelerate analysis and deliverables." },
      { icon: "CalendarClock", title: "Scheduling & Coordination", description: "Coordinate meetings, reviews and deadlines across clients and team." },
    ],
    workflows: [
      { title: "Enquiry → proposal", steps: ["New opportunity captured", "Requirements and scope gathered", "Proposal drafted from your template", "Consultant reviews and tailors", "Proposal sent and tracked"] },
      { title: "Won → onboarded", steps: ["Engagement confirmed", "Onboarding checklist triggered", "Forms and documents collected", "Access and tools provisioned", "Kickoff scheduled and briefed"] },
    ],
    modules: ["Proposal Builder", "Client Onboarding", "Project Tracking", "Reporting Agent", "Knowledge Assistant"],
    compliance: [
      "Dedicated, isolated infrastructure for client data",
      "No model training on your client or project data",
      "Australian data sovereignty and Privacy Act–first handling",
      "Audit trails across proposals, comms and reporting",
      "Permissioned access scoped per engagement",
      "Human review on client-facing deliverables",
    ],
    integrations: ["Microsoft 365", "Google Workspace", "HubSpot", "Project management tools", "CRM systems", "Document storage", "Accounting software"],
    faqs: [
      { q: "Will proposals still sound like us?", a: "Yes. The agent drafts from your templates and tone of voice; your consultants review, tailor and approve before anything goes out." },
      { q: "Can it standardise our onboarding?", a: "Absolutely. It runs the same onboarding steps every time — forms, documents, access and kickoff — so the client experience is consistent and nothing is missed." },
      { q: "Does it integrate with our project tools?", a: "In most cases, yes — with common project management and CRM tools, via integration or API. We confirm your stack during the free AI Workflow Audit." },
      { q: "How does it free up billable time?", a: "By taking proposals, onboarding, reporting and coordination off your experts' plates, so more of their week goes to the work clients actually pay for." },
    ],
  },
];

export function getIndustry(slug: string) {
  return industries.find((i) => i.slug === slug);
}
